### ISSUE TITLE
Extend TriWild to manifold geometries

### ISSUE THREAD

**Issue by jorgensd** [wildmeshing/TriWild#11]
I was wondering if TriWild could be extended for manifolds (2D surface meshes embedded in a 3D space).
From the descriptions in the TriWild paper, it seems to assume that the inputs are 2D. However, `.obj` files can take in 3D coordinates (and as seen in https://github.com/wildmeshing/TriWild/blob/master/src/triwild/triangulation.cpp#L34, it is only using the two first coordinates)

**Comment by Yixin-Hu** [comment]
Hi,

The algorithm of TriWild is designed for 2D triangle meshes only, so the code cannot be directly used for 3D planar meshes.
