### ISSUE TITLE
void triwild::feature::remove_high_curvature

### ISSUE THREAD

**Issue by dedelecoder** [wildmeshing/TriWild#4]
Hello,

I have compiled the project with visual 2017 and when i run in debug with figure 1 from pregenerated data I get an error.
it looks:
in function void triwild::feature::remove_high_curvature 
in the loop for (int j = 0; j < ranges.size(); j += 2)
in condition if (j == ranges.size() - 2) {
in loop for (double infl: old_inflection) {
in condition if (infl > ts[i][ranges[j]] && infl < ts[i][ranges[j + 1]])
the program crash because ts[i][ranges[j + 1]] generates Assertion failed: vector subscript out of range

Did you get this error?

**Comment by Yixin-Hu** [comment]
Hi,

Could you share the input files and the command you used? I tried the example of figure 1 (in https://github.com/wildmeshing/TriWild#examples-in-the-paper) as you mentioned but cannot reproduce the error. I use lldb for debugging and printed out the indices. Everything looks fine.

Thanks,
Yixin

**Comment by dedelecoder** [comment]
Hi, thank you for your reply and spending time to test. I recompiled on other computer with visual 2019 updated, and it works now. I don't know why and I am not an expert of compilation.
The command line i used was the command in the readme.txt
./Triwild --input figure1/input.obj --feature-input figure1/input.json --target-edge-length-r 0.1 --cut-holes figure1/input.xyz

**Comment by Yixin-Hu** [comment]
Ok, that's good to know.
