### ISSUE TITLE
Triwild crashes in building Figure 7 (left)

### ISSUE THREAD

**Issue by tanderson92** [wildmeshing/TriWild#9]
I am experiencing issues with a large targeted edge length. Triwild crashes when reproducing the coarsest part of Figure 7. The attached includes the errors. With the smaller values of targeted edge length reported in the paper there is no failure.

[triwild-crash.txt](https://github.com/wildmeshing/TriWild/files/9700060/triwild-crash.txt)

**Comment by Yixin-Hu** [comment]
Hi, 

Thanks for reporting the issue. The bug has been fixed.
